name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build packages
        run: moon run :build
        
      - name: Build WASM with Docker
        working-directory: packages/parser
        run: |
          # Use Docker to build WASM (faster than installing emscripten)
          npx tree-sitter build --wasm --docker
          
      - name: Run all tests
        run: moon run :test
        
      - name: Type check
        run: moon run :typecheck
        
      - name: Lint
        run: moon run :lint
        
      - name: Upload WASM artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-rcl-wasm-${{ github.sha }}
          path: packages/parser/tree-sitter-rcl.wasm
          retention-days: 7